name: Github Pages CD
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: "Step1: Checkout Code"
      uses: actions/checkout@v1

    - name: "Step2: Build And Deploy"
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: gh-pages
        BRANCH: master
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run build
