name: Node CI
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Step
      run: |
        npm install -g vuepress
        vuepress build .
      env:
        CI: true

    - name: Deploy Step
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: gh-pages
        BRANCH: master
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run build
